Trip inference initial port
cal-itp/graas pull request #323
Opened 2022-07-01 17:10 UTC by owades

Lightly tested trip inference + web app code, mostly in case you want to get a head-start on reviewing. Two big warnings:
- This produces a tripID, but I have not yet tested that it's the correct tripID
- Web app does not yet handle exceptions, such as what happens when a null trip ID is assigned.
- Currently web app asks driver to enter vehicleID. I'm curious what you think we should do.

2022-07-01 17:28 UTC, unreasonableman commented on server/app-engine/static/area.js
> +        if(lat.length > 20){
What's this all about?

2022-07-01 17:33 UTC, unreasonableman commented on server/app-engine/static/shapepoint.js
> +        let latFloat = parseFloat(lat);
The args passed into these functions appear to be strings, whereas in the python version they are numerical. Port should work the same as original wherever possible

2022-07-01 17:41 UTC, unreasonableman commented on server/app-engine/static/graas.js
> +        inf = await new TripInference('~/tmp/',agencyID, vehicleID, 15);
The constructor isn't `async` and just assigns a few instance fields, why is there an `await`?

2022-07-01 17:48 UTC, unreasonableman commented on server/app-engine/static/gtfs-rt-util.js
> +    exports.haversineDistance = async function(lat1, lon1, lat2, lon2){
Why is this `async`?

2022-07-01 17:49 UTC, unreasonableman commented on server/app-engine/static/graas.js
> +            const distance = await util.haversineDistance(lat, lon, startLat, startLon);
`haversineDistance()` is just a few calculations, why the `await`?

2022-07-01 18:04 UTC, owades commented on server/app-engine/static/area.js
> +        if(lat.length > 20){
leftover debugging, oops!

2022-07-01 19:40 UTC, unreasonableman commented on server/app-engine/static/inference.js
> +        let stop_id = await this.getStopForPosition(lat, lon, STOP_PROXIMITY);
`await` not necessary from what I can see.

2022-07-01 19:42 UTC, unreasonableman commented on server/app-engine/static/segment.js
> +    async getScore(lat, lon, seconds, shapes){
don't think this needs `async`

2022-07-01 19:44 UTC, unreasonableman requested changes
No hair-raising issues on first glance, but please fix gratuitous await/async and passing floats as strings

2022-07-05 17:20 UTC, unreasonableman commented
You probably want to understand why that is (e.g. because
haversineDistance() is declared as async).

On Tue, Jul 5, 2022 at 10:08 AM Scott Owades ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In server/app-engine/static/segment.js
> <https://github.com/cal-itp/graas/pull/323#discussion_r914018010>:
>
> > +        this.end_time = end_time
> +        this.min_file_offset = min_file_offset
> +        this.max_file_offset = max_file_offset
> +        this.waypointList = null;
> +        // util.log(`segment: id=${this.id} trip_id=${trip_id} top_left=${JSON.stringify(boundingBox.topLeft)} bottom_right=${JSON.stringify(boundingBox.bottomRight)} start_time=${util.secondsToHhmmss(start_time)} end_time=${util.secondsToHhmmss(end_time)}`);
> +    }
> +
> +    setSegmentsPerTrip(count){
> +        this.segments_per_trip = count;
> +    }
> +
> +    getTripFraction(){
> +        return this.segment_index / this.segments_per_trip;
> +    }
> +
> +    async getScore(lat, lon, seconds, shapes){
>
> At least as written now, geo_util.getMinDistance() requires an await or
> else it returns NaN.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cal-itp/graas/pull/323#discussion_r914018010>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGLQDIYFD6ADYP7GJWNOETVSRTZZANCNFSM52NKHY5Q>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-07-14 01:20 UTC, closed without merging